Update action.yml

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -131,17 +131,16 @@ runs:
           $REPO --trace sync -c --no-clone-bundle --no-tags --optimized-fetch -j$(nproc --all) --fail-fast
           
         - name: "⚡ Setup SukiSU Ultra"
-          shell: bash
-          run: |
+        shell: bash
+        run: |
           echo "🛠️ Setting up SukiSU Ultra..."
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel_platform"
-          cd kernel_workspace/kernel_platform      
-          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main          
+          cd kernel_workspace/kernel_platform
+          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
+          git submodule update --init --recursive        
           
-          git submodule update --init --recursive
-
-      - name: Apply SUSFS Patches
+     - name: Apply SUSFS Patches
         shell: bash
         run: |
           echo "Changing to configuration directory: $CONFIG..."
@@ -154,8 +153,8 @@ runs:
           cp ../../susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp ../../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
           
-          cd ./KernelSU-Next          
-         
+          cd ./KernelSU-Next
+          
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel_platform"
           cd ./KernelSU
@@ -163,8 +162,30 @@ runs:
           echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
           sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
           echo "SukiSU Ultra Version: $KSU_VERSION"
-          echo "✅ SukiSU Ultra configuration completed"         
-                    
+          echo "✅ SukiSU Ultra configuration completed"
+          
+          case "${{ inputs.susfs_branch }}" in
+            "gki-android12-5.10"|"gki-android13-5.15"|"gki-android14-6.1")
+              cp "../../../kernel_patches/next/0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch" "./ksun_susfs_latest.patch"
+              ;;
+            "gki-android15-6.6")
+              cp ../../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./
+              patch -p1 --forward --fuzz=3 < 10_enable_susfs_for_ksu.patch || true
+              cp "../../../kernel_patches/next/susfs_fix_patches/v1.5.8/fix_apk_sign.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_apk_sign.c.patch
+              cp "../../../kernel_patches/next/susfs_fix_patches/v1.5.8/fix_core_hook.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_core_hook.c.patch
+              cp "../../../kernel_patches/next/susfs_fix_patches/v1.5.8/fix_selinux.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_selinux.c.patch
+              cp "../../../kernel_patches/next/susfs_fix_patches/v1.5.8/fix_ksud.c.patch" ./
+              patch -p1 --forward --fuzz=3 < fix_ksud.c.patch
+              ;;
+            *)
+              echo "Invalid SUSFS branch: ${{ inputs.susfs_branch }}"
+              exit 1
+              ;;
+          esac
+          patch -p1 --forward < ksun_susfs_latest.patch || true                    
           case "$susfs_version" in
             "v1.5.5"|"v1.5.6"|"v1.5.7")
               cp "../../../kernel_patches/next/0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch" "./ksun_susfs_latest.patch"
