Update action.yml

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -200,29 +200,52 @@ runs:
       shell: bash
       run: |
         cd "$CONFIG"
-        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }} --depth 1
-        git clone https://github.com/ShirkNeko/SukiSU_patch.git --depth 1
+        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}
+        git clone https://github.com/ShirkNeko/SukiSU_patch.git
         cd kernel_platform
-        echo "Pulling SUSFS patches"
+        echo "Pulling susfs patches"
         cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch ./common/
         cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
         cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
+        
+        if [ "${{ github.event.inputs.ZRAM }}" = "true" ]; then
+          echo "Pulling zram patches"
+          cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux/
+          cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib/
+          cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto/
+          cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/
+        fi
+        
         cd ./common
         GKI_V="${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}"
         SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')
+        
         if [ "$GKI_V" == "android13-5.15" ] && [ "$SUBLEVEL" -lt 123 ]; then
-          echo "Fixing bugs caused by older C library support for kernel versions 5.15.0 to 5.15.123"
+          echo "Fixing some bugs caused by older C library support in kernel versions 5.15.0 to 5.15.123"
           curl -Lo fix_5.15.legacy.patch --retry 5 --retry-delay 2 --retry-connrefused https://raw.githubusercontent.com/Numbersf/Action-Build/SukiSU-Ultra/patches/fix_5.15.legacy
           patch -p1 < fix_5.15.legacy.patch
           echo "fix_5.15_patch completed"
         fi
+        
         KERNEL_VERSION="${{ env.KERNEL_VERSION }}"
         file="${{ github.event.inputs.FILE }}"
-        if [ "${{ github.event.inputs.SUSFS_ENABLE }}" = "true" ]; then
-          echo "Applying SUSFS patch"
-          patch -p1 < 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
-          echo "susfs_patch completed"
+        TRUSTY_EXISTS="false"
+        if [[ "$KERNEL_VERSION" == "6.6" ]]; then
+          if grep -q 'common-modules/trusty' "$GITHUB_WORKSPACE/.repo/manifests_fallback/${file}.xml"; then
+            TRUSTY_EXISTS="true"
+          fi
+          echo "trusty_exists=$TRUSTY_EXISTS" >> $GITHUB_OUTPUT
+        
+          if [[ "$TRUSTY_EXISTS" == "false" && "$file" != "oneplus_pad_2_pro" && "$file" != "oneplus_pad_3" ]]; then
+            echo "Fixing susfs errors caused by missing Trusty OS on some devices with kernel version 6.6"
+            sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${KERNEL_VERSION}.patch
+            sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${KERNEL_VERSION}.patch
+          fi
         fi
+        
+        echo "Applying susfs patch"
+        patch -p1 < 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
+        echo "susfs_patch completed"
 
     - name: Apply Hide Stuff Patches
       shell: bash
