Update build-kernel-release.yml

diff --git a/.github/workflows/build-kernel-release.yml b/.github/workflows/build-kernel-release.yml
--- a/.github/workflows/build-kernel-release.yml
+++ b/.github/workflows/build-kernel-release.yml
@@ -18,12 +18,9 @@ on:
         type: boolean
         default: false
       ksun_branch:
-        description: 'Choose KernelSU Next Branch'
+        description: 'Enter KernelSU Next Branch or commit hash (blank for stable tag)'
         required: true
-        type: choice
-        options:
-          - stable
-          - next
+        type: string
         default: next
       optimize_level:
         description: "Compiler optimization level"
@@ -63,48 +60,90 @@ jobs:
     name: build-batch-1 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
     strategy:
       fail-fast: false
-    matrix:
-      include:
-        - model: OP13
-          soc: sun
-          branch: oneplus/sm8750
-          manifest: oneplus_13.xml
-          android_version: android15
-          kernel_version: '6.6'
+      matrix:
+        include:
+          - model: OP11
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_11_v.xml
+            android_version: android13
+            kernel_version: '5.15'
+          - model: OP13-CN
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_13.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP13-GLO
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_13_global.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OPAce5Pro
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_ace5_pro.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP13S
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_13s.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP-PAD-3
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_pad_3.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP13T
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_13t.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP-PAD-2-PRO
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_pad_2_pro.xml
+            android_version: android15
+            kernel_version: '6.6'
+          
     runs-on: ubuntu-latest
     steps:
       - name: Select Appropriate SusFS Branch
         id: get-susfs-branch
         run: |
           KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          SUSFS_BRANCH=""
           case "$KERNEL_STRING" in
-          "android12-5.10")
-            SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch_or_commit }}"
-            ;;
-          "android13-5.10")
-            SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch_or_commit }}"
-            ;;
-          "android13-5.15")
-            SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch_or_commit }}"
-            ;;
-          "android14-5.15")
-            SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch_or_commit }}"
-            ;;
-          "android14-6.1")
-            SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch_or_commit }}"
-            ;;
-          "android15-6.6")
-            SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch_or_commit }}"
-            ;;
-          *)
-            echo "Invalid kernel version or unsupported: $KERNEL_STRING"
-            exit 1
-            ;;
+            "android12-5.10")
+              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.10")
+              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.15")
+              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-5.15")
+              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-6.1")
+              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch_or_commit }}"
+              ;;
+            "android15-6.6")
+              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch_or_commit }}"
+              ;;
+            *)
+              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
+              exit 1
+              ;;
           esac
-          if [[ -z "$SUSFS_BRANCH" ]]; then
-            SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
-          fi
-          echo "susfs_branch=$SUSFS_BRANCH" >> "$GITHUB_OUTPUT"
+
+          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
 
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -121,66 +160,106 @@ jobs:
           ksun_branch: ${{ inputs.ksun_branch }}
           susfs_commit_hash_or_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
           optimize_level: ${{ inputs.optimize_level }}
-          dry_run: ${{ inputs.dry_run }}
 
   build-batch-2:
     name: build-batch-2 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
     strategy:
       fail-fast: false
-    matrix:
-      include:
-        - model: OP12
-          soc: pineapple
-          branch: oneplus/sm8650
-          manifest: oneplus12_v.xml
-          android_version: android14
-          kernel_version: '6.1'
-        - model: OP13r
-          soc: pineapple
-          branch: oneplus/sm8650
-          manifest: oneplus_13r.xml
-          android_version: android14
-          kernel_version: '6.1'
-        - model: OP-ACE-5
-          soc: pineapple
-          branch: oneplus/sm8650
-          manifest: oneplus_ace5.xml
-          android_version: android14
-          kernel_version: '6.1'
+      matrix:
+        include:
+          - model: OP12
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus12_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP13r
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus_13r.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-ACE-5
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus_ace5.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-ACE-3V
+            soc: pineapple
+            branch: oneplus/sm7675
+            manifest: oneplus_ace_3v_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-NORD-4
+            soc: pineapple
+            branch: oneplus/sm7675
+            manifest: oneplus_nord_4_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-Nord-5
+            soc: cliffs
+            branch: oneplus/sm8635
+            manifest: oneplus_nord_5.xml
+            android_version: android14
+            kernel_version: "6.1"
+          - model: OP-PAD-2
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus_pad2_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-Ace3-Pro
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus_ace3_pro_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-Nord-CE4-LITE
+            soc: blair
+            branch: oneplus/sm6375
+            manifest: oneplus_nord_ce4_lite_5g_v.xml
+            android_version: android14
+            kernel_version: "6.1"
+          - model: OP-PAD-Pro
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus_pad_pro_v.xml
+            android_version: android14
+            kernel_version: '6.1'
     runs-on: ubuntu-latest
     steps:
       - name: Select Appropriate SusFS Branch
         id: get-susfs-branch
         run: |
           KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          SUSFS_BRANCH=""
           case "$KERNEL_STRING" in
-          "android12-5.10")
-            SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch_or_commit }}"
-            ;;
-          "android13-5.10")
-            SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch_or_commit }}"
-            ;;
-          "android13-5.15")
-            SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch_or_commit }}"
-            ;;
-          "android14-5.15")
-            SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch_or_commit }}"
-            ;;
-          "android14-6.1")
-            SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch_or_commit }}"
-            ;;
-          "android15-6.6")
-            SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch_or_commit }}"
-            ;;
-          *)
-            echo "Invalid kernel version or unsupported: $KERNEL_STRING"
-            exit 1
-            ;;
+            "android12-5.10")
+              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.10")
+              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.15")
+              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-5.15")
+              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-6.1")
+              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch_or_commit }}"
+              ;;
+            "android15-6.6")
+              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch_or_commit }}"
+              ;;
+            *)
+              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
+              exit 1
+              ;;
           esac
-          if [[ -z "$SUSFS_BRANCH" ]]; then
-            SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
-          fi
-          echo "susfs_branch=$SUSFS_BRANCH" >> "$GITHUB_OUTPUT"
+          
+          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
 
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -197,28 +276,132 @@ jobs:
           ksun_branch: ${{ inputs.ksun_branch }}
           susfs_commit_hash_or_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
           optimize_level: ${{ inputs.optimize_level }}
-          dry_run: ${{ inputs.dry_run }}
+
+  build-batch-3:
+    name: build-batch-3 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - model: OP11r
+            soc: waipio
+            branch: oneplus/sm8475
+            manifest: oneplus_11r_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP-OPEN
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_open_v.xml
+            android_version: android13
+            kernel_version: '5.15'
+          - model: OP-ACE-2
+            soc: waipio
+            branch: oneplus/sm8475
+            manifest: oneplus_ace2_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP10t
+            soc: waipio
+            branch: oneplus/sm8475
+            manifest: oneplus_10t_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP-Nord-4-CE
+            soc: crow
+            branch: oneplus/sm7550
+            manifest: oneplus_nord_ce4_v.xml
+            android_version: android13
+            kernel_version: "5.15"
+          - model: OP10pro
+            soc: waipio
+            branch: oneplus/sm8450
+            manifest: oneplus_10_pro_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP-ACE-2-PRO
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_ace2_pro_v.xml
+            android_version: android13
+            kernel_version: '5.15'
+          - model: OP12r
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_12r_v.xml
+            android_version: android13
+            kernel_version: '5.15'          
+    runs-on: ubuntu-latest
+    steps:
+      - name: Select Appropriate SusFS Branch
+        id: get-susfs-branch
+        run: |
+          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          SUSFS_BRANCH=""
+          case "$KERNEL_STRING" in
+            "android12-5.10")
+              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.10")
+              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch_or_commit }}"
+              ;;
+            "android13-5.15")
+              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-5.15")
+              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch_or_commit }}"
+              ;;
+            "android14-6.1")
+              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch_or_commit }}"
+              ;;
+            "android15-6.6")
+              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch_or_commit }}"
+              ;;
+            *)
+              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
+              exit 1
+              ;;
+          esac
+          
+          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
+
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Build Kernel
+        uses: ./.github/actions
+        with:
+          model: ${{ matrix.model }}
+          soc: ${{ matrix.soc }}
+          branch: ${{ matrix.branch }}
+          manifest: ${{ matrix.manifest }}
+          ksun_branch: ${{ inputs.ksun_branch }}
+          susfs_commit_hash_or_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
+          optimize_level: ${{ inputs.optimize_level }}
 
   trigger-release:
     needs:
       - build-batch-1
       - build-batch-2
+      - build-batch-3
     runs-on: ubuntu-latest
     if: ${{ inputs.make_release }}
     env:
       REPO_OWNER: ${{ github.repository_owner }}
       REPO_NAME: ${{ github.event.repository.name }}
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      RELEASE_NAME: 'TEST BUILD OnePlus Kernels With KernelSU Next & SUSFS v1.5.9 TEST BUILD'
+      RELEASE_NAME: '*TEST BUILD* OnePlus Kernels With KernelSU Next & SUSFS v1.5.10 *TEST BUILD*'
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          fetch-depth: 1
-
+          fetch-depth: 0
+          
       - name: Generate and Create New Tag
         run: |
-          BASE_TAG="v1.5.9-r0"
+          BASE_TAG="v1.5.11-r0"
           LATEST_TAG=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[0].name')
           if [ -z "$LATEST_TAG" ]; then
             LATEST_TAG="$BASE_TAG"
@@ -228,8 +411,8 @@ jobs:
           NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')
           echo "New tag: $NEW_TAG"
           echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
-          git tag "$NEW_TAG"
-          git push origin "$NEW_TAG"
+          git tag $NEW_TAG
+          git push origin $NEW_TAG
 
       - name: Download Artifacts
         uses: actions/download-artifact@v4
@@ -241,13 +424,16 @@ jobs:
         run: |
           echo "=== Start building the release notes ==="
           cat << EOF > release_notes.md
-          This release contains KernelSU Next and SUSFS v1.5.9
+          This release contains KernelSU Next and SUSFS v1.5.11
           
           Module: 
           -> https://github.com/sidex15/ksu_module_susfs  
           
-          Non-Official Managers:
+          Official Managers:
           -> https://github.com/KernelSU-Next/KernelSU-Next  
+          
+          Non-Official Managers:
+          -> https://github.com/WildKernels/Wild_KSU
           
           ### Built Devices
           
@@ -268,17 +454,16 @@ jobs:
           cat << 'EOF' >> release_notes.md
           
           ### Features
-          - [+] KernelSU-Next
-          - [+] SUSFS v1.5.9
+          - [+] KernelSU-Next / WildKSU Manager Support
+          - [+] SUSFS v1.5.11
           - [+] Wireguard Support
-          - [+] Maphide LineageOS Detections
-          - [+] Futile Maphide for jit-zygote-cache Detections
           - [+] Magic Mount Support
           - [+] Ptrace message leak fix for kernels < 5.16
           - [+] Manual Hooks [scope_min_manual_hooks_v1.4]
           - [+] CONFIG_TMPFS_XATTR Support [Mountify Support]
           - [+] BBR v1 Support
           - [+] HMBIRD scx support for OnePlus 13 & OnePlus Ace 5 Pro
+          - [+] Baseband Guard Support (BBG).
           EOF
           
           # Output for debugging
